on: 
  push:
    branches: [ master ]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: is version update
        run: |
          # get that commit 
          readonly local commit=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)
          if [[ $commit == !publish* ]]; then
            echo "ok"
          else
            echo "not publishing, close"
            exit 78
          fi
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: |
          npm adduser <<!
            ${{ env.username }}
            ${{ secrets.NPM_TOKEN }}
            ${{ env.email }}
          !
        env:
          username: 'redcarti'
          email: 'leakiorme@gmail.com'
      - run: npm publish
